name: CI Linux

on:
  push:
    branches: main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: linux, args: }
        - {os: windows, args: --host-toolchain mingw --copy-runtime-dlls yes}

    steps:
    - uses: actions/checkout@v2
    - uses: Trass3r/setup-cpp@master
    - run: sudo apt install -y build-essential cmake ninja-build ccache clang lld python3 python3-venv g++-mingw-w64-x86-64
    - run: echo "CCACHE_DIR=$GITHUB_WORKSPACE/.ccache" >> $GITHUB_ENV
    - name: ccache cache files
      uses: actions/cache@v2
      with:
        path: .ccache
        key: clang-${{ matrix.config.os }}-ccache
    - name: build
      run: |
        ccache -z
        ./setup.sh
        . ./venv/bin/activate
        build.py --use-ninja --use-ccache ${{ matrix.config.args }}
        ccache -s
    - run: tar cvf llvm-embedded.tar.bz2 ./install-*/*
    - uses: actions/upload-artifact@v2
      with:
        path: llvm-embedded.tar.bz2
