name: CI Linux

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Trass3r/setup-cpp@master
    - run: sudo apt install -y build-essential cmake ninja-build clang lld python3 python3-venv
    - name: build
      run: |
        ./setup.sh
        . ./venv/bin/activate
        build.py --use-ninja
    - uses: actions/upload-artifact@v2
      with:
        path: ./install-*
