name: CI

on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: linux, args: ''}
        - {os: windows, args: --host-toolchain mingw --copy-runtime-dlls yes}

    steps:
    - uses: actions/checkout@v2
    - uses: Trass3r/setup-cpp@master
    - run: sudo apt install -y build-essential cmake ninja-build ccache clang lld python3 python3-venv g++-mingw-w64-x86-64
    - uses: hendrikmuhs/ccache-action@v1
      with:
        key: clang-${{ matrix.config.os }}
        max-size: 2.5G
    - name: build
      run: |
        ccache -z
        ./setup.sh
        . ./venv/bin/activate
        build.py --use-ninja --use-ccache ${{ matrix.config.args }} --variants armv7em_hard_fpv4_sp_d16 armv7em_hard_fpv5_d16 armv7em_soft_nofp armv7m_soft_nofp
        ccache -s
    - run: cd install-*/LLVM* && tar cfa llvm-embedded.tar.xz *
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.config.os }} build
        path: install*/*/llvm-embedded.*
