name: CI Linux

on:
  push:
    branches: main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Trass3r/setup-cpp@master
    - run: sudo apt install -y build-essential cmake ninja-build ccache clang lld python3 python3-venv
    - run: echo "CCACHE_DIR=$GITHUB_WORKSPACE/.ccache" >> $GITHUB_ENV
    - name: ccache cache files
      uses: actions/cache@v2
      with:
        path: build/.ccache
        key: clang-linux-ccache
    - name: build
      run: |
        ./setup.sh
        . ./venv/bin/activate
        build.py --use-ninja --use-ccache
    - uses: actions/upload-artifact@v2
      with:
        path: ./install-*
